apiVersion: v1
kind: Service
metadata:
  name: kafka-pulsar-service
  labels:
    app: kafka-pulsar-service
spec:
  ports:
    - port: 8080
  selector:
    app: kafka-pulsar-service
  type: LoadBalancer
